# Site settings
title: "ADaPT - Adaptive Data Pipeline Toolkit"
description: "A Python-based, YAML-configured data pipeline framework for extracting, transforming, and exporting data from various sources to multiple destinations."
baseurl: "/ADaPT-ETL"
url: "https://karthick-jaganathan.github.io"

# Logo and favicon
logo: "/assets/images/adapt-logo.svg"
# favicon_ico: "/assets/images/favicon.ico"

# Repository information
repository: "karthick-jaganathan/ADaPT-ETL"

# Build settings
markdown: kramdown
highlighter: rouge
remote_theme: just-the-docs/just-the-docs

# Kramdown settings
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache

# Navigation
header_pages:
  - index.md
  - installation.md
  - packages/index.md
  - examples.md
  - diagrams.md
  - api-reference.md
  - contributing.md

# Collections
collections:
  packages:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "packages"
    values:
      layout: "package"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/



# SEO settings
author: "Karthick Jaganathan"
twitter:
  username: kjaganathan
  card: summary

# Social links
github_username: karthick-jaganathan

# Google Analytics (optional)
# google_analytics: UA-XXXXXXXX-X

# Just the Docs theme configuration
color_scheme: adapt
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Enable copy code button
enable_copy_code_button: true

# Aux links for header
aux_links:
  "GitHub Repository":
    - "https://github.com/karthick-jaganathan/ADaPT-ETL"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Footer content
footer_content: "Copyright &copy; 2024 ADaPT Project. Distributed under the <a href=\"https://github.com/karthick-jaganathan/ADaPT-ETL/blob/master/LICENSE\">Apache License 2.0</a>."

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Callouts
callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red 